# Generated by Django 4.0.2 on 2022-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('full_text', models.TextField(verbose_name='Makala')),
                ('genre', models.CharField(default=None, max_length=50, verbose_name='Genre')),
                ('language', models.CharField(default=None, max_length=2, verbose_name='Language')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
                ('author', models.CharField(default=None, max_length=50, verbose_name='Author')),
                ('location', models.CharField(default=None, max_length=50, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Мақала',
                'verbose_name_plural': 'Мақалалар',
            },
        ),
    ]
