# Generated by Django 4.0.2 on 2022-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('telnumber', models.IntegerField(verbose_name='Telephone number')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактілер',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Rapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='Nickname')),
                ('label', models.CharField(max_length=30, verbose_name='Label')),
                ('genre', models.CharField(max_length=15, verbose_name='Genre')),
                ('tracks', models.TextField(max_length=100, verbose_name='Tracks')),
            ],
            options={
                'verbose_name': 'Орындаушы',
                'verbose_name_plural': 'Орындаушылар',
                'ordering': ['nick'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Track name')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist nickname')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Тректер',
                'ordering': ['title'],
            },
        ),
    ]
